### ISSUE TITLE
future_sapply() does not support FUN specified as a character string, e.g. FUN = "[["

### ISSUE THREAD

**Issue by jpjoines** [HenrikBengtsson/future.apply#105]
**Describe the bug**
`future_sapply()` does not recognize the double bracket extract function, `[[`, as a function.

**Reproduce example**
`library( future.apply )`
> Loading required package: future

`numcores <- parallel::detectCores() - 1`
`numcores`
> [1] 23

`plan( multicore, workers = numcores )`
`id.vc <- c( "1:99", "1:562", "999:3", "999:71", "999:150", "476142:43" )`
`loci.vc <- future_sapply( strsplit( id.vc, ":" ), "[[", 1 )`
> Error: ‘is.function(FUN)’ is not TRUE

**Expected behavior**
        Work as a drop-in replacement for `base::sapply()`
`loci.vc <- sapply( strsplit( id.vc, ":" ), "[[", 1 )`
`loci.vc`
> [1] "1"      "1"      "999"    "999"    "999"    "476142"

`position.vc <- sapply( strsplit( id.vc, ":" ), "[[", 2 )`
`position.vc`
> [1] "99"  "562" "3"   "71"  "150" "43" 

**Session information**
`sessionInfo()`
> R version 4.2.1 (2022-06-23)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Rocky Linux 8.6 (Green Obsidian)

> Matrix products: default
BLAS/LAPACK: /usr/local/lib/libopenblasp-r0.3.20.so

> locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C              
 [3] LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8    
 [5] LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8   
 [7] LC_PAPER=en_US.UTF-8       LC_NAME=C                 
 [9] LC_ADDRESS=C               LC_TELEPHONE=C            
[11] LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       

> attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

> other attached packages:
[1] future.apply_1.9.1 future_1.28.0     

> loaded via a namespace (and not attached):
[1] compiler_4.2.1    parallelly_1.32.1 tools_4.2.1       parallel_4.2.1   
[5] listenv_0.8.0     codetools_0.2-18  digest_0.6.30     globals_0.16.1

**Comment by HenrikBengtsson** [comment]
Thanks for reporting.  It's interesting that I completely missed imitating this behavior of the base-R functions.  This affects all the **future.apply** functions.  This should be fixed, because the contract with this package is that it should emulate the API of the base-R functions as far as possible.

FYI, it is much better to use backticks around the `FUN` object than specify it by its name, i.e. use

```r
loci.vc <- sapply( strsplit( id.vc, ":" ), `[[`, 1 )
```

instead of

```r
loci.vc <- sapply( strsplit( id.vc, ":" ), "[[", 1 )
```

So, if you use the backticks variant, it'll work with all **future.apply** functions, including the one you used in your example.

PS. Have a look at <https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax#quoting-code>.  It'll show you how to wrap code in code blocks using three backticks; you don't want to use single backticks for blocks of code.

**Comment by jpjoines** [comment]
Thanks for the tips!

**Comment by HenrikBengtsson** [comment]
This has now been fixed in the next release;

## Bug Fixes

 * Functions `future_eapply()`, `future_lapply()`, `future_sapply()`, and `future_vapply()` failed if `FUN` was specified as the name of a function rather than the function object itself, e.g. `future_lapply(1:3, FUN = "sqrt")`.


Until that's on CRAN, you can install the devel version as:

```r
remotes::install_github("HenrikBengtsson/future.apply", ref="develop")
```

Thanks again for reporting.

**Comment by HenrikBengtsson** [comment]
future.apply 1.10.0 fixing this is now on CRAN
