### ISSUE TITLE
If `X` contains globals, they are not found

### ISSUE THREAD

**Issue by DavisVaughan** [HenrikBengtsson/future.apply#12]
Hey Henrik, I've discovered a bug in `furrr` and wanted to pass it along as it applies to `future.apply` as well.

`X` could be a list of functions, and these functions could have globals themselves. Right now, `X` isn't checked for globals, only `FUN` is!

See below where you only look for globals in `FUN`.
https://github.com/HenrikBengtsson/future.apply/blob/master/R/future_lapply.R#L140

I've fixed this for myself by also adding a `getGlobalsAndPackages()` call for `X`.

(note that this code works with `multicore` on Mac because of forked processes having access to the global env, I think)

``` r
library(future.apply)
library(purrr)

plan(multisession)

# Can't find me!
my_robust_sum <- function(x) {
  sum(x, na.rm = TRUE)
}

multi_x <- list(
  c(1, 2, NA),
  c(2, 3, 4)
)

# The Xs that you map over are partially filled functions.
# This means the Xs can have globals as well!
Xs <- map(multi_x, ~ partial(my_robust_sum, .x))

Xs
#> [[1]]
#> function (...) 
#> my_robust_sum(.x, ...)
#> <environment: 0x7fa2e93361f0>
#> 
#> [[2]]
#> function (...) 
#> my_robust_sum(.x, ...)
#> <environment: 0x7fa2e93241f0>

future_lapply(
  X = Xs, 
  FUN = function(.x) {
    .x()
  }
)
#> Error in my_robust_sum(.x, ...): could not find function "my_robust_sum"
```

**Comment by HenrikBengtsson** [comment]
Thanks for troubleshooting and sharing. It sounds like a reasonable workaround to add `getGlobalsAndPackages(X)`.

**Comment by HenrikBengtsson** [comment]
Here's a minimal reproducible example (that also can be used as a package test for this).
```r
library("future.apply")
a <- 42
b <- 21
X <- list(function(b) 2 * a, function() b / 2, function() a + b, function() 3.14)

plan(sequential)
y <- future_lapply(X, FUN = function(f) f())
str(y)
List of 4
 $ : num 84
 $ : num 10.5
 $ : num 63
 $ : num 3.14

plan(multisession)
y <- future_lapply(X, FUN = function(f) f())
# Error in f() : object 'a' not found
```

This example also brings up the question whether we're wanna export all globals found in `X` to _all_ workers (= futures), or we should identify globals in `X` per chunk (= per future/per worker)?  On the other hand, if there are lots of chunks, searching for globals for each chunk might introduce a significant overhead.  Maybe one could do:

1. Check whether there are any globals in `X` upfront.
2. If globals are detected in `X`, then search each chunk for globals, otherwise not.

A refined version of (2) could be to check whether any of the globals found in (1) are large or small (by some some threshold).  If they're small, then one could export them to all workers and skip the per-chunk search.  Similarly, if there are not too many chunks (by some threshold), then one could skip the per-chunk search.  Maybe the "skip" rule should be a function of (total global size in `X`, number of chunks).

I'll add support for the absolute minimum, i.e. find globals upfront and then export to all futures.

**Comment by HenrikBengtsson** [comment]
Update: Since scanning `X` for globals already involves going through `X` element by element, one can effectively scan `X` for globals using something like `globals_X <- lapply(X, FUN = getGlobalsAndPackages, ...)` such that `length(globals_X) == length(X)`. Then it's quick to chunk also these.
