### ISSUE TITLE
Workflow for reproducing future_lapply results

### ISSUE THREAD

**Issue by matherealize** [HenrikBengtsson/future.apply#31]
First of all, thanks for this package which has saved me a lot of headache in various complicated parallelisation settings. :)

**Question**
Proper reproduction of future_lapply results - is the following workflow reliable and future-proof (no pun intended):

- Inside the simulation function, store random seeds (via .Random.seed or using future.apply:::get_random_seed)
- Pass saved seeds to future_lapply as list of pre-generated random seeds

**Request**
If yes, then something like the following example could be added to the manpage.

```R
library(parallel)
library(future.apply)

sim_fct = function(i) {
    list(seed = future.apply:::get_random_seed(), 
         data = rnorm(100))
}

# define seeds using simple integer
cl = makeCluster(2)
plan(cluster, workers = cl)
res = future_lapply(1:10, sim_fct, future.seed = 42)
stopCluster(cl)

# test reproducibility of individual result using different plan
plan(sequential)
res_5 = future_lapply(1, sim_fct, future.seed = list(res[[5]]$seed))

all.equal(res[[5]]$data, res_5[[1]]$data)
```

**Background**
Coming from foreach-dorng to future, I was looking for an equivalent of doRNG's attr(result, "rng") which automatically stores random seeds. It took me a bit of fiddling and reading the source to actually get results to reproduce using future_lapply (especially the part of passing stored seeds as a list). I think a simple example like this could add clarity and prevent uncertainty how to do it.

**Comment by HenrikBengtsson** [comment]
Thanks, I'm glad you find it useful.

I would do:
```r
X <- 1:10

# Pregenerate seeds - one per element in X
# Note, this is invariant to current future backend and number of workers
seeds <- future_lapply(X, FUN = function(x) .Random.seed, future.seed=42L)

# Reproducible usage of seeds
# Note, this is invariant to current future backend and number of workers
y <- future_lapply(X, FUN = function(x) rnorm(1L) + x, future.seed = seeds)
```

At some point I think it makes sense to export `future.apply:::get_random_seed()` (or whatever it will be called that day), because I think it is useful also outside of the future.apply framework.  However, there are other features I'd like to add and test out before settling on the design, e.g. Issue #20 is another use case that we might want to support.  Until that is in place, the above "workaround" for pre-creating seeds is the safest to use for now.

I'll think about it, but having `future_lapply()` and friends add extra attributes might bite us later and might even break some code.  Because of this, I'm really trying to stick to `future_lapply()` returning the exact same value as if `lapply()` was used.

I'll add it to the todo list to include the above to the help or the vignette.

**Comment by matherealize** [comment]
Thanks, that answers my question. I will implement seeding according to your suggestion and +1 the idea to add to the vignette.

**Comment by HenrikBengtsson** [comment]
Now added to Section 'Reproducible random number generation (RNG)' in `help("future_lapply")`.
