### ISSUE TITLE
Performance of future_apply vs apply

### ISSUE THREAD

**Issue by Nowosad** [HenrikBengtsson/future.apply#39]
Hi @HenrikBengtsson. 
Thanks for all your great work in futureverse - it is very useful.
Lately I've been trying to add the future.apply support to the stars package (https://github.com/r-spatial/stars/issues/124). To my surprise, I found out that using `future_apply` is about twice slower than regular `apply`. 
See a reprex below:

``` r
# two options -------------------------------------------------------------
library(future.apply)
#> Loading required package: future
future_fun = function(X, MARGIN, FUN, ..., CLUSTER = 1) {
  fn = function(y, ...) {
    ret = if (CLUSTER == 1)
      apply(y, MARGIN, FUN, ...)
    else if (CLUSTER == 2) {
      future_apply(y, MARGIN, FUN, ...)
    } 
    ret
  }
  ret = lapply(X, fn) 
}

X = list(array(data = 1:255, dim = c(1440, 720, 9)))

plan(multiprocess)
system.time(future_fun(X, 1:2, mean, CLUSTER = 1))
#>    user  system elapsed 
#>   4.178   0.029   4.215
system.time(future_fun(X, 1:2, mean, CLUSTER = 2))
#>    user  system elapsed 
#>   6.680   0.381   7.683
```

<sup>Created on 2019-03-09 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

This issue does not happen when using the parApply function:

<details> <summary>Examples with three methods</summary>

``` r
library(future.apply)
#> Loading required package: future
library(parallel)
future_fun = function(X, MARGIN, FUN, ..., CLUSTER = 1) {
  fn = function(y, ...) {
    ret = if ("cluster" %in% class(CLUSTER)){
      parApply(CLUSTER, y, MARGIN, FUN, ...)
    } else if (CLUSTER == 1)
      apply(y, MARGIN, FUN, ...)
    else if (CLUSTER == 2) {
      future_apply(y, MARGIN, FUN, ...)
    } 
    ret
  }
  ret = lapply(X, fn) 
}

X = list(array(data = 1:255, dim = c(1440, 720, 9)))

plan(multiprocess)
cl = makeCluster(getOption("cl.cores", 2))
system.time(future_fun(X, 1:2, mean, CLUSTER = 1))
#>    user  system elapsed 
#>   4.034   0.033   4.076
system.time(future_fun(X, 1:2, mean, CLUSTER = 2))
#>    user  system elapsed 
#>   6.651   0.367   7.638
system.time(future_fun(X, 1:2, mean, CLUSTER = cl))
#>    user  system elapsed 
#>   1.649   0.024   3.514
```

<sup>Created on 2019-03-09 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>
</details>

**Comment by HenrikBengtsson** [comment]
Hi. Thanks and thanks for reporting.  

From a quick view, it turns out that the built-in protection against too large globals is the bottleneck here.  I've added a section below explaining this. This check can be disabled by setting option `future.globals.maxSize` to `+Inf`.  For example:
```r
library(future.apply)
library(parallel)
cl <- makeCluster(2L)
plan(cluster, workers = cl)

X <- array(data = 1:255, dim = c(1440, 720, 9))

t0 <- system.time(y0 <- apply(X, MARGIN = 1:2, FUN = mean))
t0
##   user  system elapsed 
##  5.044   0.036   5.081 

t1 <- system.time(y1 <- parApply(cl, X, MARGIN = 1:2, FUN = mean))
t1
##   user  system elapsed 
##  2.327   0.077   4.455 

t2 <- system.time(y2 <- future_apply(X, MARGIN = 1:2, FUN = mean))
t2
##   user  system elapsed 
##  7.551   0.052  10.176

options(future.globals.maxSize = +Inf)
t2b <- system.time(y2 <- future_apply(X, MARGIN = 1:2, FUN = mean))
t2b
##   user  system elapsed 
##  2.501   0.020   5.004 
```

# Overhead validation size of globals

`future_apply()` uses a very similar implementation as `parApply()`.  Specifically, they both use `seq_along(X)` and `MARGIN = 1:2` to split up `X` into a _list_ `Xsets` which are then processed by `parLapply()` and `future_lapply()`, respectively.  It is for this `Xsets` list, which in this case is of length 1,036,800, that it takes a lot of time to calculate the total size for.   It's the length that is the dominant factor of slowness here.  For example, on an "empty" list of 1,036,800 it takes 5s:
```r
> system.time(future:::objectSize(vector("list", length=1036800)))
   user  system elapsed 
  5.026   0.000   5.025
```
Setting `future.globals.maxSize=+Inf` skips this step/penalty time.

IDEA: As a quick workaround, it should be possible to lower the risk for this overhead by calculating the size on `X` before splitting up in `Xsets`.  I think this is the one that is most likely to be implemented first.

IDEALLY: Implement a much faster version of `future:::objectSize()`.  Unfortunately, this is not obvious.  One could calculate it as `size <- length(serialize(Xsets, connection = NULL))`, which is much faster, but that will allocate a temporary raw vector of size `size` bytes.  One could also disable the max-size check of globals for certain backends, say, those running on the local machine, cf. https://github.com/HenrikBengtsson/future/issues/197.


# parApply() vs future_apply()

So, if `parApply()` and `future_apply()` use very similar implementations, why is that latter slower than the former.  The reason is that the future stack comes with a bit more overhead.  

First, it scans for globals automatically by default.  You can disable that/set globals manually via argument `future.globals`.  This overhead is often very small.  Another overhead comes from the fact that standard output is captured for futures, which effectively adds the overhead of `capture.output()` to each future.  This can be disabled by `future.stdout = NA`.  There is also an overhead added to the evaluation of futures that comes from the fact that we need to take care of evaluation errors and relay them up to the master process.  Basically, each future is evaluated in a `tryCatch()` - you cannot disable this.  The parallel package is really not the best in handling such errors.

```r
> options(future.globals.maxSize = +Inf)

> t2b <- system.time(y2 <- future_apply(X, MARGIN = 1:2, FUN = mean))
> t2b
   user  system elapsed 
  2.501   0.020   5.004 

> t2c <- system.time(y2 <- future_apply(X, MARGIN = 1:2, FUN = mean, future.globals = FALSE, future.stdout = NA))
> t2c
   user  system elapsed 
  1.703   0.052   4.174 
```

Furthermore, for _cluster_ futures, which run on persistent background R workers, the memory of the worker is cleaned up for each future lowering the overall load on the machine - this adds a few more rounds of communication - not much, but it adds to it.  Another is the check that the cluster node connections are still valid - something that can happen and something that R really should take care of - see https://github.com/HenrikBengtsson/Wishlist-for-R/issues/81 for the mess it can cause.  There are a few other small things too.


# Smarter implementation of future_apply()?

The current implementation relying of `future_lapply()` as the workhorse was the most straightforward and the fact that the parallel package does the same made me use that.  It's also the solution that should work for all types/classes of `X`.  But, for certain  types of `X` and choices of `MARGIN` one might be able implement more efficient solutions


PS. Above I used `plan(cluster, workers = cl)` so make the comparison toward `parallel::parApply()` as fair as possible.  Using `plan(multiprocess)` is platform specific but more importantly the number of workers depends on the number of cores on the machine.  We could have used `plan(multisession, workers=2)` for a fair comparison.

**Comment by Nowosad** [comment]
@HenrikBengtsson thank you for this complete and interesting explanation. I've learned a ton here. 

What is, in your opinion, the best approach to incorporate `future_apply()` in a package expecting the size of globals issue? Does setting A inside another function make any sense?

**Comment by HenrikBengtsson** [comment]
"Does setting A inside .."??

**Comment by Nowosad** [comment]
Sorry, I meant "Does setting `options(future.globals.maxSize = +Inf)` inside another function make any sense?"

**Comment by HenrikBengtsson** [comment]
Yes, I think it's a valid workaround for this slowness (until fixed). Just make sure to undo it with a `on.exit(options(oopts))` so that the option remain untouched outside regardless what happens.

**Comment by HenrikBengtsson** [comment]
The overhead in `future_apply()` from validation size of globals has now been reduced significantly.  Available in the develop branch.

**Comment by HenrikBengtsson** [comment]
future.apply 1.4.0, where this has been fixed, is now on CRAN.
