### ISSUE TITLE
Feature request: purrr-like sugar functions

### ISSUE THREAD

**Issue by pat-s** [HenrikBengtsson/future.apply#52]
Similar as in [mlr3misc](https://github.com/mlr-org/mlr3misc/blob/ff64b6c9539126734120afd938d5f235b78fa8ba/R/purrr_map.R).
Essentially just wrapping the existing `future_*` ones to have some syntactic sugar.

It seems like that [furrr](https://github.com/DavisVaughan/furrr) is not actively developed anymore and supporting the purrr syntax could give {future.apply} quite a push.

If you are ok with it, I could do a PR.

**Comment by HenrikBengtsson** [comment]
Hi. So, future.apply should stick to its mission and support futurized version of the base R apply family and nothing else.  That makes it very clear what it provides and doesn't and whenever there's an update in base R it is very clear what future.apply needs to update.

Having said that, this doesn't mean that what you need could fit in a separate package.  But for my understanding, and I'm not up-to-date with the latest in purrr; are you saying it's API has been updated/expanded so that furrr is not out of date?

PS. I do have plans to extract parts of the future.apply package into a "helper" package that provides utility functions that future.apply package and others like furrr can make use of.  That way future.apply and furrr etc. can be even lighter.

**Comment by pat-s** [comment]
> Having said that, this doesn't mean that what you need could fit in a separate package. But for my understanding, and I'm not up-to-date with the latest in purrr; are you saying it's API has been updated/expanded so that furrr is not out of date?

No. I just would like to have wrappers around future_apply functions that provide type safe returns like in {purrr} and to be able to just prefix `purrr::map()` calls with `future_` without the need to rely on {furrr} but only on {future.apply}.

Specifically I mean the `map_chr()`, `map_dfr()` and all of its friends.
Please have a look at what we do in [mlr3misc](https://github.com/mlr-org/mlr3misc/blob/ff64b6c9539126734120afd938d5f235b78fa8ba/R/purrr_map.R).
I would like to see future-like versions of such in {future.apply}.
I am not talking about the `~` notation used within {purrr}.

I also do not like depending on a package like {furrr} which has not seen a commit in 2 years (even though it might still work). Lately I ported all my parallel appy calls from {furrr} to {future.apply} and this is when I came up with this thought.

Since these would only be convenience wrappers there should be no need for any updates. And base R updated of future_apply funs would just populate through.

I am not sure if there is a need to have multiple packages just to use type safe variants / different notation of future-parallelized apply functions?

**Comment by HenrikBengtsson** [comment]
Thxs. I think I understand a bit better now but still to get a little bit more examples on where you wanna head.  

So, first of all, if {furrr} would be up-to-date and maintained on a regular basis, then all would be good, or?

Second, taking `purrr::map_int()` as an example, for which there's already `furrr::future_map_int()`, what would you expect that to look like in terms of base R apply and future.apply syntax?  Would it be `future_lapply_int()`?

PS. There's also the `plyr` API which is closely related to base R apply functions.  That one could be futurized, as an alternative to the current `.parallel = TRUE` + doFuture approach.

**Comment by pat-s** [comment]
> So, first of all, if {furrr} would be up-to-date and maintained on a regular basis, then all would be good, or?

Yes and no. Why not?

I do not see a reason why there is a need for X packages implementing future-based parallel approaches. I would want to have one package/framework. Having {furrr} and {future.apply} doing essentially the same just using different notation is confusing. Also joining forces might reduce redundant work.

As a user I want to simply prefix `future_` to all apply functions out there - whether type-safe variants of `map()` or base R apply funs.

> Second, taking purrr::map_int() as an example, for which there's already furrr::future_map_int(), what would you expect that to look like in terms of base R apply and future.apply syntax? Would it be future_lapply_int()?

Yes, `future_lapply_int()`. Essentially I would like to have typesafe lapply()/sapply() variants. Not sure about the naming since the return of `future_lapply_int()` would not be a list but an integer vector. That's probably also why {purrr} uses the generic `map()` instead of `lapply()`.

Besides, variants like `*_dfr()` also really add some value since they do an `rbindlist()` in the background.

As shown in {mlr3misc} most of these variants are just some wrappers, often not longer than three lines of code. 

Essentially I would like to have one future-based apply package which comes with type-safe variants on top of all futurized R base apply functions.

**Comment by HenrikBengtsson** [comment]
> I do not see a reason why there is a need for X packages implementing future-based parallel approaches. I would want to have one package/framework. Having {furrr} and {future.apply} doing essentially the same just using different notation is confusing. 

Here I disagree.  The benefit with the base apply <-> future.apply, purrr <-> furrr mapping is that the implementation and testing of the futurized API is well defined.  There is no need for the maintainer to worry about features, corner cases, etc.  All test cases can be replicated in the futurized version.  It is also very clear to end-users what to expect and not.  Anything with a `future_` prefix should work identically to the non-futurized version.  Not more, not less. (**)


> Also joining forces might reduce redundant work.

This is the role of the 'future' package - it simplifies futurizing higher-level APIs, which the 'future.apply', 'furrr', and 'doFuture' packages are evidence of.  As I implied in a previous comment, I'm also considering a 'future.mapreduce'-ish package that can further serve common needs of 'future.apply' et al. packages and that does not really fit in the lower-level 'future' package.  This package will provide utility functions for chunking, parallel RNGs, etc. so the maintainers won't have to worry about the details on those.  This package will remove redundant parts of 'future.apply' and 'furrr' - removing this type of redundancy benefits everyone - direct and indirect developers and users.

Regarding an `future_lapply_nnn()` API:

From my experience on just implementing future.apply and setting up a solid set of tests for its correctness, I predict it will be major work to get correct and there will be a need for many releases before things are stable.  Testing will be essential.  

For me to even consider breaking the design goal of having future.apply (=implementing only what's in base R apply functions and nothing else), I'd really like to see a complete and mature implementation of this.  Because of this, I think it makes more sense to implement this in a 'future.apply.extras' package first and let this new API mature there before anything else.  Such a package should probably also implement non-futurized versions of this API, i.e. `lapply_nnn()`, because this is not only about lack of functionality of future.apply but also a lack of functionality in base R.  When this is stable, then maybe it's more clear whether it should belong to future.apply or not.  But, because of (**) above, I'm hesitant.

**Comment by pat-s** [comment]
> Anything with a future_ prefix should work identically to the non-futurized version.

Yeah I see. Fair enough :)

> This package will remove redundant parts of 'future.apply' and 'furrr' - removing this type of redundancy benefits everyone - direct and indirect developers and users.

👍 

>  I think it makes more sense to implement this in a 'future.apply.extras' package first and let this new API mature there before anything else. Such a package should probably also implement non-futurized versions of this API, i.e. lapply_nnn(), because this is not only about lack of functionality of future.apply but also a lack of functionality in base R

Fully agree, good point!

Well written and good thoughts, Henrik! This will be helpful for many people to make things clearer regarding the parallel universe in R.
