### ISSUE TITLE
future.apply::future_lapply() processes never complete

### ISSUE THREAD

**Issue by adamhsparks** [HenrikBengtsson/future.apply#74]
I've noted just recently that one of my packages that uses this function, [GSODR](https://github.com/ropensci/GSODR/blob/63b1ea87afb1a80dc1c48ac37e3cada90b8a0db3/R/internal_functions.R#L325) was failing in CI. Checking logs didn't indicate anything really amiss, just that runs were being cancelled.

When I started looking into it, it seems that the `future.apply::future_lapply()` isn't completing, it just keeps running. When I run tests locally it does not stop, but if I swap out for just the base `lapply()` it works fine. I can't see in the history of my package's code that I've changed anything before this started failing, so I'm confused here. I thought that `future_lapply()` should just swap in for `lapply()`, and it has for some time until now. Has something changed and I need to adjust my code? Looking at the docs, I can't find anything. 

Sorry for opening the issue but I'm stumped here with this one.

**Comment by HenrikBengtsson** [comment]
> I thought that future_lapply() should just swap in for lapply(), and it has for some time until now.

Correct, you should certainly be able to swap an `lapply()` with a `future_lapply()`, especially when using the `plan(sequential)`.  

> Has something changed and ...

I've rolled out future 1.21.0 (2020-12-10) and parallelly 1.22.0 (2020-12-13).   Did your troubles start before those releases?  If so, that's a clue.

> ... I need to adjust my code?

Nope.

I've been in devs long enough that nothing surprises me these days and at the end of the day there's always an easy answer.  Let's try to figure out what's going on.  I suggest that you add the following to your GitHub Actions workflow:

```yaml
env:
  R_FUTURE_DEBUG: TRUE
```

That will enable debug output from both **parallelly** and **future**.  This should leave enough breadcrumbs in the output logs for us to narrow in on exactly where it stalls.   For example, if **future.apply** is not loaded previously, it could be something when loading the package, it could be related to the `future_lapply()` function, the low-level future framework, or a specific future backend.  Hopefully the debug output will tell.

**Comment by HenrikBengtsson** [comment]
BTW, if this hits the 6-hour limit on GHA, maybe there's a way to lower that limit so it times out soon.

**Comment by adamhsparks** [comment]
Thanks, Henrik,
I think it started around 10/12, that would sound about right.

I've set the time limit to 30 minutes to time out sooner and set 

```yaml
env:
  R_FUTURE_DEBUG: TRUE
```

We'll see what we can find.

**Comment by adamhsparks** [comment]
Are you able to access the logs? https://github.com/ropensci/GSODR/runs/1553443266?check_suite_focus=true

If not, I've attached the archive here with the debug enabled.

[logs_522.zip](https://github.com/HenrikBengtsson/future.apply/files/5692056/logs_522.zip)

**Comment by HenrikBengtsson** [comment]
Where should I look; is it failing on all OSes or only on a specific OS?

**Comment by HenrikBengtsson** [comment]
Also, since it looks like it stalls when it checks the package examples, we need to get ahold of the content of the `GSODR.Rcheck/GSODR-Ex.Rout` file that `R CMD check GSODR_1.2.3.tar.gz` (or similar) produces.

**Comment by adamhsparks** [comment]
It fails on all OSes, including macOS locally. Is there a good way for me to generate what you need locally?

**Comment by HenrikBengtsson** [comment]
We need `GSODR.Rcheck/GSODR-Ex.Rout` from where it stalls, so it has to come from GA unless you can reproduce it locally.  I was hoping it was part of the failed dump.    

I don't know GA well enough to tell you how to do it.  Since it times out, I guess it has to be done in one of those "Post" steps.  If you could get a `cat GSODR.Rcheck/GSODR-Ex.Rout` to be called, then it would show up in the GA logs, I guess.

**Comment by adamhsparks** [comment]
Let me see what I can do.

**Comment by HenrikBengtsson** [comment]
Also, just to rule out problems that might be related to parallel processing, are we sure that `future.apply::future_lapply()` runs with the default 'sequential' plan?  

If the recent **parallelly** or **future** did indeed introduced a bug, another approach would be to show this by installing the older versions, i.e. adding a GA "run" entry prior to package checks:
```
run: |
   echo -e 'options(Ncpus = 4, pkgType = "source", repos = structure(c(CRAN = "https://cloud.r-project.org/")))' > $HOME/.Rprofile
   install.packages("https://cloud.r-project.org/src/contrib/Archive/parallelly/parallelly_1.21.0.tar.gz")
   install.packages("https://cloud.r-project.org/src/contrib/Archive/future/future_1.20.1.tar.gz")
```

Also for poor man's troubleshooting, could you remove (not just `\dontrun{} / \donttest{}`) all examples but one, so we could narrow down on a specific function call stack for where the stall happens?  That might help rule some things out.


FWIW, the revdep checks on GSODR were just fine for both [**parallelly**](https://github.com/HenrikBengtsson/future/blob/master/revdep/README.md) and [**future**](https://github.com/HenrikBengtsson/future/blob/master/revdep/README.md).  I ran those on a CentOS 7 system giving each package two cores to play with (GA gives two cores per job too).  Also, [**data.table**](https://cran.r-project.org/web/packages/data.table/) was updated on 2020-12-08 and [CRAN reports on fork errors on several of the platforms](https://cran.r-project.org/web/checks/check_results_data.table.html), so that could also be a suspect (although I don't know why it would work with `lapply()`).

**Comment by adamhsparks** [comment]
I suspected you’d done revdep checks on this, so I was surprised to see this as well.

Yesterday I’d run just a regular old sequential job for `get_gsod()` for a single station locally. It failed. If I swapped in `lapply()` it worked.

Thank you for your kind assistance so far! I’ll keep digging.

**Comment by HenrikBengtsson** [comment]
A few more suggestions:

1. It looks like your `\examples{}` use `\donttest{}`, which means they shouldn't be tested unless `--run-donttest` is used.  I'm not sure what `--as-cran` does, but since it seems to stall when check examples, I would start by removing all your `\examples{}` make sure it continues to the package tests.  Then I would add back a minimal example and see if it stalls.  It could be that it stall simply by your package being attached.
 
2. **[globals](https://cran.r-project.org/web/packages/globals/)** 1.14.0 was released on 2020-11-22.  Maybe worth a shot to retry with the previous version - globals 1.13.1 (2020-10-11).  OTH, since your package passes all checks on CRAN, this is certainly an odd one.

3. I suspect everything is supposed to run sequentially already, but if not, yet another thing is to force sequential processing by setting:

```r
env:
  R_FUTURE_AVAILABLECORES_FALLBACK: 1
```

**Comment by adamhsparks** [comment]
Thanks. Note that Ii’s not just `\examples{}` failing. Tests fail and the actual function, `get_GSOD()` fails to complete when used interactively, it will just keep running. This bug was reported to me via e-mail by a new user who was unable to use the package. 

I’m mid-move between states right now and still in an Airbnb until we move into our new place in a few days. And to top it off, I just got my new laptop as my previous one’s battery bulged, which I discovered just two days before the removalists showed up. I tinkered a bit more this morning with the new computer. It still exhibits the same behaviour on the new laptop.

But now that I have a computer and soon a place to live, I can work on this some more. Glad it’s not failing on CRAN (yet) that would not be good.

**Comment by HenrikBengtsson** [comment]
Wow, yeah, that's a lot on your plate right now. Best wishes for moving and settling down.

**Comment by adamhsparks** [comment]
🙏, I’ll get it figured out. Glad to have your support with this, that helps greatly.

**Comment by taraskaduk** [comment]
I am experiencing the same issue as described above. I first blamed it on a brand-new laptop with M1 chip and a clean install of R, but seems like that is not the issue.

I don't a set of sophisticated debugging skills and you folks, but if I can help debug this in any way - I'd be happy to help.

**Comment by adamhsparks** [comment]
With everything I've got going right now, moving and starting a new job, plus CRAN whinging about another issue "failing", I just removed the parallel functionality from GSODR for now. It's not optimal, but I'd rather have the package actually functional than not.

I'll try to find time to revisit this in the future. 😅
